package pl.orange.gpon;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2016-05-01T12:48:52.817+02:00
 * Generated source version: 3.1.6
 * 
 */
@WebServiceClient(name = "MpService", 
                  wsdlLocation = "file:/home/atos/workspace/CXFAsyncCall/src/main/resources/wsdl/GPONInsider.wsdl",
                  targetNamespace = "http://mp.channels.overlay.tp.atos.pl/") 
public class MpService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://mp.channels.overlay.tp.atos.pl/", "MpService");
    public final static QName MpChannelPort = new QName("http://mp.channels.overlay.tp.atos.pl/", "MpChannelPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/home/atos/workspace/CXFAsyncCall/src/main/resources/wsdl/GPONInsider.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(MpService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/home/atos/workspace/CXFAsyncCall/src/main/resources/wsdl/GPONInsider.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public MpService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public MpService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MpService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public MpService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public MpService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public MpService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns MpChannel
     */
    @WebEndpoint(name = "MpChannelPort")
    public MpChannel getMpChannelPort() {
        return super.getPort(MpChannelPort, MpChannel.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MpChannel
     */
    @WebEndpoint(name = "MpChannelPort")
    public MpChannel getMpChannelPort(WebServiceFeature... features) {
        return super.getPort(MpChannelPort, MpChannel.class, features);
    }

}
