/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'atos' at '4/30/16 5:47 PM' with Gradle 2.6
 *
 * @author atos, @date 4/30/16 5:47 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
